### ISSUE TITLE
# Uses Camera Property

### ISSUE THREAD

**Issue by VPS-Crypto** [VPS-Crypto/sonatype-#3]
# Uses Camera Property
Resolves the new feature request/issue at #2090 by prompting for permissions for the camera, and saving camera permission settings on a project level (as with the location permission right now).

# Tests
* Previously, I could not get the camera to work (prior to this PR) using the WebView. After the changes, setting the property to checked will work correctly, prompting for the camera permission and then enabling it properly.

* Tested Android permission requests before & after explicit request change; It fixed my Map permissions which I've had issues prior to this PR

* Microphone permission works fine on compiled apks on request

# TODOs
- [x] ~GeoLocation permissions might have broken. I could not get map websites to work. I am investigating into this now, but could not see a valid reason for this occurring~ (Seems like an issue on my setup?)
- [x] Add microphone permissions
- [x] ~Add clearMicrophone for microphone permissions~ (not standard as with GeoLocation)
- [x] ~Add clearCamera for camera permissions?~ (not standard as with GeoLocation)
- [x] ~~Change past tests to accommodate for new change~~

__Originally posted by @elatoskinas in https://github.com/mit-cml/appinventor-sources/pull/2096__
